services:

  db:
    image: postgres
    container_name: justhost_app_db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASS
      POSTGRES_DB: $DB_NAME
      POSTGRES_PORT: $DB_PORT
    volumes:
     - postgres_data:/var/lib/postgresql/data
  app:
    image: justhost_app
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - dev

  dev:
    image: test
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    command: python manage.py test
    depends_on:
      - db

volumes:
  postgres_data: