# Generated by Django 5.1.5 on 2025-02-05 13:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VPS',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('cpu', models.PositiveIntegerField()),
                ('ram', models.PositiveIntegerField()),
                ('hdd', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('started', 'STARTED'), ('blocked', 'BLOCKED'), ('stopped', 'STOPPED')], default='started')),
            ],
            options={
                'verbose_name': 'vps',
                'db_table': 'vps',
            },
        ),
    ]
